ZSH_DIR="$HOME/.config/zsh"
source "$ZSH_DIR/env.sh"
source "$ZSH_DIR/load.zsh"
source "$ZSH_DIR/keybindings.zsh"
source "$ZSH_DIR/alias.sh"
source "$ZSH_DIR/history.zsh"
source "$ZSH_DIR/completion.zsh"
