#!/bin/bash

clear
if [ $(git rev-parse --is-inside-work-tree 2>/dev/null) ]; then
    default_branch=$(git branch --show-current)
    branches=($(git branch --format="%(refname:short)"))
    printf "Git Branches\n---\n$(git --no-pager branch -vv --color=always)\n---\n"
    read -p "Switch to branch? (Press ENTER to ignore): " select_branch
    if [[ -z "$select_branch" ]]; then
        exit 0
    fi
    if ! printf "%s\n" "${branches[@]}" | grep -qx "$select_branch"; then
        echo "Branch \"$select_branch\" did not exist"
        read -p "Press any key to continue ... " -n 1 -r
        exit 1
    fi
    git checkout "$select_branch"
else
    echo "Not in git repo"
fi
read -p "Press any key to continue ... " -n 1 -r
