#!/bin/sh

if ! [ -f "$1" ] && ! [ -h "$1" ]; then
    exit 0
fi

width="$2"
height="$3"
x="$4"
y="$5"

hash() {
    printf "%s/.cache/lf/%s" "$HOME" \
        "$(stat --printf "%n\0%i\0%F\0%s\0%W\0%Y" -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
}

draw() {
    ueberzugpp cmd -s "$UB_SOCKET" -a add -i PREVIEW -x "$x" -y "$y" --max-width "$width" --max-height "$height" -f "$1"
    exit 1
}

draw_cache() {
    if [ -f "$1" ]; then
        draw "$1"
    fi
}

case "$1" in
    *.7z|*.a|*.ace|*.alz|*.arc|*.arj|*.bz|*.bz2|*.cab|*.cpio|*.deb|*.gz|*.jar|\
    *.lha|*.lrz|*.lz|*.lzh|*.lzma|*.lzo|*.rar|*.rpm|*.rz|*.t7z|*.tar|*.tbz|\
    *.tbz2|*.tgz|*.tlz|*.txz|*.tZ|*.tzo|*.war|*.xz|*.Z|*.zip)
        als -l "$1"
        exit 0
        ;;
    *.md)
        mcat --sc "${width}x${height}" --theme gruvbox --color always "$1"
        exit 0
        ;;
    *.iso)
        iso-info --no-header "$1"
        exit 0
        ;;
    *.odt|*.ods|*.odp|*.sxw)
        odt2txt "$1"
        exit 0
        ;;
    *.docx)
        docx2txt "$1" -
        exit 0
        ;;
    *.svg)
        if [ -n "$UB_SOCKET" ]; then
            cache="$(hash "$1").jpg"
            draw_cache "$cache"
            magick -density 300 "$1" "$cache"
            draw "$cache"
        fi
        ;;
esac

case "$(file -Lb --mime-type -- "$1")" in
    text/troff)
        man -- "$1" | bat --language man
        exit 0
        ;;
    text/*)
        bat --line-range=:100 "$1"
        exit 0
        ;;
    application/json)
        cat "$1" | jq -C
        exit 0
        ;;
    application/pdf)
        if [ -n "$UB_SOCKET" ]; then
            cache="$(hash "$1")"
            draw_cache "$cache.jpg"
            pdftoppm -f 1 \
                -singlefile \
                -jpeg \
                -- "$1" "$cache"
            draw "$cache.jpg"
        else
            pdftotext -nopgbrk -q -- "$1" -
            exit 0
        fi
        ;;
    image/*)
        if [ -n "$UB_SOCKET" ]; then
            draw "$1"
        fi
        ;;
    audio/*)
        ffprobe -i "$1" -loglevel quiet -show_format -pretty
        exit 0
        ;;
    video/*)
        if [ -n "$UB_SOCKET" ]; then
            cache="$(hash "$1").jpg"
            draw_cache "$cache"
            ffmpegthumbnailer -i "$1" -o "$cache" -s 0
            draw "$cache"
        fi
        ;;
esac

header_text="File Type Classification"
header=""
len="$(( ($width - (${#header_text} + 2)) / 2 ))"
if [ $len -gt 0 ]; then
    for i in $(seq "$len"); do
        header="-$header"
    done
    header="$header $header_text "
    for i in $(seq "$len"); do
        header="$header-"
    done
else
    header="$header_text"
fi
printf "\033[7m%s\033[0m\n" "$header"
file -Lb -- "$1" | fold -s -w "$width"
exit 0
