#!/bin/zsh

clear
IFS=$'\n'
for file in ${=fx}; do
    case "$file" in
        *.7z|*.rar|*.tar|*.tar.gz|*.tgz|*.zip)
            als -l "$file" 2> /dev/null
            printf "---\n$file\n"
            read "ans?Process unarchive? [Y/n] "
            case "$ans" in
                [Yy]*)
                    unpackDir="$(pwd)/"
                    printf "---\nUnarchive in?\n"
                    vared unpackDir
                    mkdir -p $unpackDir
                    aunpack "$file" -X "$unpackDir"
                    ;;
            esac
            ;;
        *)
            echo "Unsupported format of $file"
            read -sk1 "?Press any key to continue ..."
            ;;
    esac
done
