#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10

ibus-daemon -d &
mate-power-manager &
nm-applet &
feh --bg-scale ~/Pictures/background.jpg &
compton &
