#!/bin/sh

config_dir="./.config"
local_dir="./.local"
sys_dir="./system"

cp_to_dir() {
    eval dir="\${$#}"
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
    cp -r $@
}
cp_func=$(declare -f cp_to_dir)

while read -p "Install AUR helper & packages? [Y/n] " reply; do
    case $reply in
        [Nn]*) break;;
        [Yy]*)
            if [ ! -d "/tmp/paru-bin" ]; then
                git clone https://aur.archlinux.org/paru-bin.git /tmp/paru-bin
            fi
            (cd /tmp/paru-bin && makepkg -si)
            pkg="$(cat ./pkglist)"
            while read -p "Install packages with touchpad utils? [Y/n] " touchpad; do
                case $touchpad in
                    [Yy]*)
                        sudo bash -c "$cp_func; cp_to_dir $sys_dir/01-touchpad.conf /etc/X11/xorg.conf.d/"
                        cp_to_dir $config_dir/libinput-gestures.conf $HOME/.config/
                        break;;
                    [Nn]*)
                        pkg=$(echo "$pkg" | sed "/^# touchpad utils/,/^$/d")
                        break;;
                esac
            done
            while read -p "Install packages with bluetooth utils? [Y/n] " bluetooth; do
                case $bluetooth in
                    [Yy]*)
                        sudo bash -c "$cp_func; cp_to_dir $sys_dir/01-touchpad.conf /etc/X11/xorg.conf.d/"
                        break;;
                    [Nn]*)
                        pkg=$(echo "$pkg" | sed "/^# bluetooth/,/^$/d")
                        break;;
                esac
            done
            pkg=$(echo "$pkg" | sed "s/^#.*//")
            paru -S $pkg
            if [ ! -e /usr/local/bin/vim ]; then
                sudo mkdir -p /usr/local/bin/
                sudo ln -s /usr/bin/nvim /usr/local/bin/vim
            fi
            break;;
    esac
done

while read -p "Install dwm? [Y/n] " reply; do
    case "$reply" in
        [Nn]*) break;;
        [Yy]*)
            git clone https://github.com/eeeXun/dwm.git $HOME/.config/dwm/
            git clone https://github.com/eeeXun/dwmblocks.git $HOME/.config/dwmblocks/
            sudo make -C $HOME/.config/dwm/ install clean
            sudo make -C $HOME/.config/dwmblocks/ install clean
            sudo bash -c "$cp_func; cp_to_dir $sys_dir/dwm.desktop /usr/share/xsessions/"
            mkdir -p $HOME/.local/share/
            cp_to_dir $local_dir/share/dwm/ $HOME/.local/share/
            break;;
    esac
done

while read -p "Set up bspwm? [Y/n] " reply; do
    case "$reply" in
        [Nn]*) break;;
        [Yy]*)
            cp_to_dir $config_dir/bspwm/ $config_dir/sxhkd/ $config_dir/polybar/ \
                $HOME/.config/
            break;;
    esac
done

while read -p "Set up i3? [Y/n] " reply; do
    case "$reply" in
        [Nn]*) break;;
        [Yy]*)
            cp_to_dir $config_dir/i3/ $config_dir/i3status/ $HOME/.config/
            break;;
    esac
done

while read -p "Defalut session? (1) dwm (2) bspwm (3) mate (4) i3 (n) no : " reply; do
    case "$reply" in
        1|dwm) session="dwm";;
        2|bspwm) session="bspwm";;
        3|mate) session="mate";;
        4|i3) session="i3";;
        n|no) break;;
        *) continue;;
    esac
    sudo sed -i "s/^#\?user-session=.*/user-session=$session/" /etc/lightdm/lightdm.conf
    break
done

while read -p "Terminal emulator? (1) st (2) termite (3) alacritty (n) no : " reply; do
    case "$reply" in
        1|st)
            git clone https://github.com/eeeXun/st.git $HOME/.config/st/
            sudo make -C $HOME/.config/st/ install clean
            sudo bash -c "$cp_func; cp_to_dir $sys_dir/st.desktop /usr/share/applications/"
            break;;
        2|termite)
            cp_to_dir $config_dir/termite/ $HOME/.config/
            break;;
        3|alacritty)
            cp_to_dir $config_dir/alacritty/ $HOME/.config/
            break;;
        n|no) break;;
    esac
done

while read -p "Set up script? [Y/n] " reply; do
    case "$reply" in
        [Nn]*) break;;
        [Yy]*)
            sudo bash -c "$cp_func; cp_to_dir $sys_dir/lf_run $sys_dir/rmundo /usr/local/bin"
            cp_to_dir $local_dir/bin/ $HOME/.local/
            break;;
    esac
done

while read -p "Set up other config? [Y/n] " reply; do
    case "$reply" in
        [Nn]*) break;;
        [Yy]*)
            cp_to_dir $config_dir/nvim/ $config_dir/black $config_dir/stylua/ \
                $config_dir/lf/ $config_dir/rofi/ $config_dir/dircolors \
                $config_dir/gtk-3.0/ $config_dir/zsh/ $config_dir/tmux/ \
                $config_dir/zathura/ $config_dir/nsxiv/ $config_dir/dunst/ \
                $config_dir/bat/ $config_dir/picom.conf \
                $config_dir/sql-formatter.json $HOME/.config/
            cp ./.zshrc ./.profile ./.tmux.conf ./.Xresources $HOME/
            chsh -s /bin/zsh
            echo "export HISTFILE=$HOME/.cache/bash_history" >> $HOME/.bashrc
            git config --global user.email "sdes96303@gmail.com"
            git config --global user.name "eeeXun"
            break;;
    esac
done
