#!/bin/sh

config_dir="./config"
local_dir="./local"
other_dir="./other"

cp_to_dir() {
    eval dir="\${$#}"
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
    cp -r $@
}
cp_func=$(declare -f cp_to_dir)

common_setup() {
    if [ ! -d "/tmp/yay-bin" ]; then
        git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
    fi
    (cd /tmp/yay-bin && makepkg -si)
    if [ ! -L /usr/local/bin/vim ]; then
        sudo mkdir -p /usr/local/bin/
        sudo ln -s /usr/bin/nvim /usr/local/bin/vim
    fi
    cp_to_dir $config_dir/non-gui/* $HOME/.config/
    cp ./.zshrc ./.zprofile $HOME/
    sudo bash -c "$cp_func; cp_to_dir $other_dir/lf_run /usr/local/bin"
    cp_to_dir $local_dir/bin/ $HOME/.local/
    chsh -s /bin/zsh
    echo 'export HISTFILE="$HOME/.cache/bash_history"' >> $HOME/.bashrc
    # gradle
    mkdir -p $HOME/.cache/gradle/
    echo 'org.gradle.daemon=false' > $HOME/.cache/gradle/gradle.properties
}

while read -p "Install with GUI? [Y/n] " reply; do
    case $reply in
        [Nn]*)
            pkg="$(cat ./pkglist | sed "1,/^### GUI/d" | sed "/^#/d")"
            yay -S $pkg
            common_setup
            exit 0;;
        [Yy]*)
            pkg="$(cat ./pkglist)"
            while read -p "Install with bluetooth? [Y/n] " bluetooth; do
                case $bluetooth in
                    [Yy]*)
                        break;;
                    [Nn]*)
                        pkg=$(echo "$pkg" | sed "/^# bluetooth/,/^$/d")
                        break;;
                esac
            done
            while read -p "Install on laptop? [Y/n] " laptop; do
                case $laptop in
                    [Yy]*)
                        # touchpad
                        sudo bash -c "$cp_func; cp_to_dir $other_dir/01-touchpad.conf /etc/X11/xorg.conf.d/"
                        cp_to_dir $config_dir/libinput-gestures.conf $HOME/.config/
                        break;;
                    [Nn]*)
                        pkg=$(echo "$pkg" | sed "/^# laptop utils/,/^$/d")
                        break;;
                esac
            done
            pkg=$(echo "$pkg" | sed "/^#/d")
            yay -S $pkg
            common_setup
            cp_to_dir $config_dir/gui/* $HOME/.config/
            cp ./.xprofile ./.Xresources $HOME/
            # dark theme
            gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
            # xdg user-dirs
            xdg-user-dirs-update
            sudo sed -i "s/^enabled=True/enabled=False/" /etc/xdg/user-dirs.conf
            # lightdm
            sudo sed -i -E "/^#greeter-session=/s/^#([[:alpha:]-]+)=.*/\1=lightdm-slick-greeter/" \
                /etc/lightdm/lightdm.conf
            sudo systemctl enable lightdm
            # pipewire
            systemctl --user enable pipewire
            # wireshark
            sudo usermod -aG wireshark $USER
            # bluetooth
            case $bluetooth in
                [Yy]*)
                    sudo systemctl enable bluetooth
                    break;;
            esac
            # laptop
            case $laptop in
                [Yy]*)
                    # brightnessctl & libinput-gestures
                    sudo usermod -aG input $USER
                    break;;
            esac
            break;;
    esac
done

while read -p "Install dwm? [Y/n] " reply; do
    case "$reply" in
        [Nn]*) break;;
        [Yy]*)
            git clone https://github.com/eeeXun/dwm.git $HOME/.config/dwm/
            git clone https://github.com/eeeXun/dwmblocks.git $HOME/.config/dwmblocks/
            sudo make -C $HOME/.config/dwm/ install clean
            sudo make -C $HOME/.config/dwmblocks/ install clean
            sudo bash -c "$cp_func; cp_to_dir $other_dir/dwm.desktop /usr/share/xsessions/"
            cp_to_dir $local_dir/share/dwm/ $HOME/.local/share/
            break;;
    esac
done

while read -p "Defalut login session? (1) dwm (2) mate (n) no : " reply; do
    case "$reply" in
        1|dwm) session="dwm";;
        2|mate) session="mate";;
        n|no) break;;
        *) continue;;
    esac
    sudo sed -i -E "/^#user-session=/s/^#([[:alpha:]-]+)=.*/\1=$session/" /etc/lightdm/lightdm.conf
    break
done

while read -p "Install st? [Y/n] " reply; do
    case "$reply" in
        [Nn]*) break;;
        [Yy]*)
            git clone https://github.com/eeeXun/st.git $HOME/.config/st/
            sudo make -C $HOME/.config/st/ install clean
            sudo bash -c "$cp_func; cp_to_dir $other_dir/st.desktop /usr/share/applications/"
            break;;
    esac
done
