alias l="ls"
alias la="ls -a"
alias ll="ls -lh"
alias ls="ls --color=auto"
alias lla="ls -alh"
alias diff="diff -u --color"
alias grep="grep --color=auto"
alias history="history -$HISTSIZE"
alias lf="lf_run"
