#!/bin/sh

while read file; do
    case "$1" in
        "w")
            feh --no-fehbg --bg-scale "$file";;
        "y")
            echo "$file" | sed "s/^/file:\/\//" | xclip -selection clipboard \
                -target text/uri-list
            notify-send "$file" "Copied to clipboard"
            ;;
        "r")
            convert -rotate 90 "$file" "$file";;
        "R")
            convert -rotate -90 "$file" "$file";;
        "h")
            convert -flop "$file" "$file";;
        "v")
            convert -flip "$file" "$file";;
    esac
done
