#!/bin/sh

while read file; do
    case "$1" in
        "w")
            feh --no-fehbg --bg-scale "$file";;
        "y")
            type="$(file -Lb --mime-type -- "$file")"
            xclip -selection clipboard -target "$type" -i "$file"
            notify-send "$file copied to clipboard"
            ;;
        "r")
            convert -rotate 90 "$file" "$file";;
        "R")
            convert -rotate -90 "$file" "$file";;
        "h")
            convert -flop "$file" "$file";;
        "v")
            convert -flip "$file" "$file";;
    esac
done
