#!/bin/sh

while read file
do
    case "$1" in
        "w")
            feh --bg-scale "$file";;
        "y")
            echo "$file" | tr -d '\n' | xclip -selection clipboard
            notify-send "$file copied to clipboard";;
        "r")
            convert -rotate 90 "$file" "$file";;
        "R")
            convert -rotate -90 "$file" "$file";;
        "h")
            convert -flop "$file" "$file";;
        "v")
            convert -flip "$file" "$file";;
    esac
done
