#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          10
bspc config focused_border_color "#e60053"
bspc config pointer_modifier  mod4

ibus-daemon -d &
mate-power-manager &
nm-applet &
feh --bg-scale ~/Pictures/background2.jpg &
compton &
