require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "asm",
        "bash",
        "bibtex",
        "c",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "doxygen",
        "git_rebase",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "groovy",
        "html",
        "http",
        "java",
        "javadoc",
        "javascript",
        "json",
        "latex",
        "lua",
        "markdown",
        "markdown_inline",
        "printf",
        "python",
        "rasi",
        "rust",
        "scala",
        "solidity",
        "sql",
        "ssh_config",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xresources",
        "yaml",
        "zathurarc",
    },
    highlight = {
        enable = true,
        disable = function(lang, buf)
            return lang == "latex" or vim.fn.fnamemodify(vim.api.nvim_buf_get_name(buf), ":t") == "diffpanel_3"
        end,
    },
})
